use std::{
    env,
    fs,
    path::{Path, PathBuf},
};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let i18n_dir = manifest_dir.join("i18n");

    println!("cargo:rerun-if-changed=i18n");

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let out_file = out_dir.join("i18n_embedded.rs");

    let code = generate_embedded_i18n(&i18n_dir);
    fs::write(&out_file, code).expect("failed to write i18n_embedded.rs");
}

fn generate_embedded_i18n(i18n_dir: &Path) -> String {
    let mut locales: Vec<(String, Vec<PathBuf>)> = Vec::new();

    if let Ok(entries) = fs::read_dir(i18n_dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir()
                && let Some(locale) = path.file_name().and_then(|s| s.to_str())
            {
                let ftl_files = collect_ftl_files(&path);
                if !ftl_files.is_empty() {
                    locales.push((locale.to_string(), ftl_files));
                }
            }
        }
    }

    locales.sort_by(|a, b| a.0.cmp(&b.0));

    let mut out = String::new();

    out.push_str("// AUTO-GENERATED by build.rs — DO NOT EDIT\n\n");
    out.push_str("use fluent_bundle::FluentResource;\n\n");

    out.push_str("pub fn available_locales() -> &'static [&'static str] {\n");
    out.push_str("    &[\n");
    for (locale, _) in &locales {
        out.push_str(&format!("        \"{}\",\n", locale));
    }
    out.push_str("    ]\n}\n\n");

    out.push_str("pub fn load_locale(locale: &str) -> Option<Vec<FluentResource>> {\n");
    out.push_str("    let resources: Vec<FluentResource> = match locale {\n");

    for (locale, files) in &locales {
        out.push_str(&format!("        \"{}\" => vec![\n", locale));
        for ftl in files {
            let ftl_path = ftl.display().to_string().replace('\\', "/");
            out.push_str(&format!(
                "            FluentResource::try_new(include_str!(r#\"{}\"#).to_string()).unwrap(),\n",
                ftl_path
            ));
        }
        out.push_str("        ],\n");
    }

    out.push_str("        _ => return None,\n");
    out.push_str("    };\n");
    out.push_str("    Some(resources)\n");
    out.push_str("}\n");

    out
}

fn collect_ftl_files(dir: &Path) -> Vec<PathBuf> {
    let mut files = Vec::new();

    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().and_then(|e| e.to_str()) == Some("ftl") {
                files.push(path);
            }
        }
    }

    files.sort();
    files
}
