[general]
init_timeout = 15
keyboard_enabled = true
mouse_enabled = true

[gpu]
backend = "VULKAN"
vsync = false

[logging]
level = "info"

[mappings]
initial_state = true
show_notification = true
toggle = "F10"

[[mappings.profiles]]
device_id = "10AF971ZLN004SU"
name = "AskTao"
rotation = 1

[[mappings.profiles.mappings]]
action = "Tap"
key = "Q"
x = 2593
y = 614

[[mappings.profiles.mappings]]
action = "Tap"
key = "F"
x = 172
y = 836

[[mappings.profiles.mappings]]
action = "Tap"
key = "X"
x = 708
y = 1066

[[mappings.profiles.mappings]]
action = "Tap"
key = "F1"
x = 830
y = 80

[[mappings.profiles.mappings]]
action = "Tap"
key = "D"
x = 303
y = 840

[[mappings.profiles.mappings]]
action = "Tap"
key = "Tab"
x = 346
y = 81

[[mappings.profiles.mappings]]
action = "Tap"
key = "F2"
x = 706
y = 77

[[mappings.profiles.mappings]]
action = "Tap"
key = "Backslash"
x = 164
y = 78

[[mappings.profiles.mappings]]
action = "Tap"
key = "Num2"
x = 2395
y = 619

[[mappings.profiles.mappings]]
action = "Tap"
key = "W"
x = 2185
y = 31

[[mappings.profiles.mappings]]
action = "Tap"
key = "Num3"
x = 2563
y = 456

[[mappings.profiles.mappings]]
action = "Tap"
key = "A"
x = 2596
y = 1155

[[mappings.profiles.mappings]]
action = "Tap"
key = "Z"
x = 2482
y = 376

[[mappings.profiles.mappings]]
action = "Tap"
key = "Space"
x = 1599
y = 777

[[mappings.profiles.mappings]]
action = "Tap"
key = "Num5"
x = 2245
y = 459

[[mappings.profiles.mappings]]
action = "Tap"
key = "Num6"
x = 2400
y = 452

[[mappings.profiles.mappings]]
action = "Tap"
key = "V"
x = 2485
y = 527

[[mappings.profiles.mappings]]
action = "Tap"
key = "C"
x = 2105
y = 1066

[[mappings.profiles.mappings]]
action = "Tap"
key = "S"
x = 2597
y = 824

[[mappings.profiles.mappings]]
action = "Tap"
key = "T"
x = 2274
y = 74

[[mappings.profiles.mappings]]
action = "Tap"
key = "B"
x = 2630
y = 1012

[[mappings.profiles.mappings]]
action = "Tap"
key = "G"
x = 2232
y = 880

[scrcpy.options]
stay_awake = true
turn_screen_off = true

[scrcpy.v4l2]
buffer = 0
capture_orientation = 270
device = "/dev/video0"

[scrcpy.video]
bit_rate = "24M"
codec = "h264"
encoder = "c2.mtk.avc.encoder"
max_fps = 60
max_size = 1600
