//! Mapping configuration UI
//!
//! Handles displaying existing mappings and adding/removing mappings
//! through user interaction. Includes modal dialogs for key input and confirmations.

use {
    super::{
        super::{
            coords::{MappingCoordSys, ScrcpyCoordSys, VisualCoordSys},
            utils::extract_position,
        },
        dialog::{ModalDialog, ModalDialogResult},
        theme::AppColors,
    },
    crate::{
        config::mapping::{Key, KeyMapping},
        saide::coords::MappingPos,
        t,
        tf,
    },
    eframe::egui::{self, Color32, FontId, Pos2, Stroke},
    egui::Modifiers,
};

pub struct MappingDrawParams<'a> {
    pub mappings: &'a KeyMapping,
    pub profile_name: Option<&'a str>,
    pub video_rect: egui::Rect,
    pub visual_coords: &'a VisualCoordSys,
    pub scrcpy_coords: &'a ScrcpyCoordSys,
    pub mapping_coords: &'a MappingCoordSys,
}
/// Events generated by the mapping config window
#[derive(Debug, Clone)]
pub enum MappingConfigEvent {
    None,
    Close,
    RequestAddMapping(Pos2),
    RequestDeleteMapping(Pos2),
    RequestRenameProfile,
    RequestCreateProfile,
    RequestDeleteProfile,
    RequestSaveAsProfile,
    RequestShowHelp,
}

/// Mapping configuration UI state
pub struct MappingConfigWindow {
    /// Whether the config window is visible
    pub visible: bool,

    /// Pending key input position (percentage coordinates 0.0-1.0)
    pos: Option<MappingPos>,

    /// Input dialog state
    key_input_dialog: ModalDialog,
    key: Option<Key>,

    /// Delete confirmation dialog state
    delete_mapping_dialog: ModalDialog,
    delete_target_key: Option<Key>,
    delete_target_pos: Option<MappingPos>,

    /// Override confirmation dialog state
    override_mapping_dialog: ModalDialog,
    override_key: Option<Key>,
    override_pos: Option<MappingPos>,
    override_new_pos: Option<MappingPos>,

    /// Rename profile dialog state
    rename_dialog: ModalDialog,

    /// Help dialog state
    help_dialog: ModalDialog,
}

impl MappingConfigWindow {
    pub fn new() -> Self {
        Self {
            visible: false,

            pos: None,

            key_input_dialog: ModalDialog::new("key_input_dialog")
                .with_title(&t!("mapping-config-dialog-create-title"))
                .with_key_capture(true),
            key: None,

            delete_mapping_dialog: ModalDialog::new("delete_mapping_dialog")
                .with_title(&t!("mapping-config-dialog-delete-title")),
            delete_target_key: None,
            delete_target_pos: None,

            override_mapping_dialog: ModalDialog::new("override_mapping_dialog")
                .with_title(&t!("mapping-config-dialog-override-title")),
            override_key: None,
            override_pos: None,
            override_new_pos: None,

            rename_dialog: ModalDialog::new("rename_profile_dialog")
                .with_title(&t!("mapping-config-dialog-rename-title"))
                .with_text_input(&t!("mapping-config-dialog-rename-placeholder")),

            help_dialog: ModalDialog::new("help_dialog")
                .with_title(&t!("mapping-config-help-title")),
        }
    }

    pub fn toggle(&mut self) {
        self.visible = !self.visible;
        if !self.visible {
            self.reset();
        }
    }

    pub fn hide(&mut self) {
        self.visible = false;
        self.reset();
    }

    fn reset(&mut self) {
        self.pos = None;

        self.key_input_dialog.reset();
        self.key = None;

        self.delete_mapping_dialog.reset();
        self.delete_target_key = None;
        self.delete_target_pos = None;

        self.override_mapping_dialog.reset();
        self.override_key = None;
        self.override_pos = None;
        self.override_new_pos = None;

        self.rename_dialog.reset();

        self.help_dialog.reset();
    }

    pub fn is_visible(&self) -> bool { self.visible }

    pub fn draw(&mut self, ctx: &egui::Context, params: MappingDrawParams) -> MappingConfigEvent {
        if !self.visible {
            return MappingConfigEvent::None;
        }

        let mut event = MappingConfigEvent::None;
        let colors = AppColors::from_context(ctx);

        egui::Area::new(egui::Id::new("mapping_config_overlay"))
            .fixed_pos(params.video_rect.min)
            .interactable(false)
            .order(egui::Order::Middle)
            .show(ctx, |ui| {
                let painter = ui.painter();

                painter.rect_filled(
                    params.video_rect,
                    0.0,
                    Color32::from_rgba_premultiplied(0, 0, 0, 180),
                );

                painter.text(
                    Pos2::new(params.video_rect.center().x, params.video_rect.top() + 20.0),
                    egui::Align2::CENTER_TOP,
                    t!("mapping-config-title"),
                    FontId::proportional(18.0),
                    Color32::WHITE,
                );

                let instructions = [
                    t!("mapping-config-instruction-help"),
                    t!("mapping-config-instruction-exit"),
                ];
                instructions.iter().enumerate().for_each(|(i, text)| {
                    painter.text(
                        Pos2::new(
                            params.video_rect.center().x,
                            params.video_rect.top() + 50.0 + i as f32 * 20.0,
                        ),
                        egui::Align2::CENTER_TOP,
                        text,
                        FontId::proportional(12.0),
                        Color32::LIGHT_GRAY,
                    );
                });

                params.mappings.read().iter().for_each(|(key, action)| {
                    if let Some(percent_pos) = extract_position(action) {
                        let screen_pos = params.visual_coords.from_mapping(
                            &percent_pos,
                            &params.video_rect,
                            params.scrcpy_coords,
                            params.mapping_coords,
                        );

                        painter.circle_filled(screen_pos, 12.0, colors.mapping_circle_fill);
                        painter.circle_stroke(
                            screen_pos,
                            12.0,
                            Stroke::new(2.0, colors.mapping_circle_stroke),
                        );

                        let key_text = format!("{:?}", key);
                        painter.text(
                            Pos2::new(screen_pos.x, screen_pos.y - 15.0),
                            egui::Align2::CENTER_BOTTOM,
                            &key_text,
                            FontId::proportional(12.0),
                            Color32::WHITE,
                        );
                    }
                });

                if let Some(name) = params.profile_name {
                    let profile_text = format!("{} {}", t!("mapping-config-profile-label"), name);
                    painter.text(
                        Pos2::new(
                            params.video_rect.center().x,
                            params.video_rect.top() + 100.0,
                        ),
                        egui::Align2::CENTER_TOP,
                        &profile_text,
                        FontId::proportional(14.0),
                        Color32::LIGHT_GRAY,
                    );
                }
            });

        ctx.input(|input| {
            if input.pointer.primary_clicked()
                && !self.any_dialog_open()
                && let Some(click_pos) = input.pointer.interact_pos()
                && params.video_rect.contains(click_pos)
            {
                event = MappingConfigEvent::RequestAddMapping(click_pos);
            }

            if input.pointer.secondary_clicked()
                && !self.any_dialog_open()
                && let Some(click_pos) = input.pointer.interact_pos()
                && params.video_rect.contains(click_pos)
            {
                event = MappingConfigEvent::RequestDeleteMapping(click_pos);
            }
        });

        if !self.any_dialog_open() {
            ctx.input_mut(|input| {
                for e in &input.events {
                    if let egui::Event::Key {
                        key,
                        pressed: true,
                        repeat: false,
                        modifiers,
                        ..
                    } = e
                    {
                        match key {
                            egui::Key::Escape if modifiers.is_none() => {
                                event = MappingConfigEvent::Close;
                                input.consume_key(Modifiers::NONE, egui::Key::Escape);
                                break;
                            }
                            egui::Key::F1 if modifiers.is_none() => {
                                event = MappingConfigEvent::RequestShowHelp;
                                input.consume_key(Modifiers::NONE, egui::Key::F1);
                                break;
                            }
                            egui::Key::F2 if modifiers.is_none() => {
                                event = MappingConfigEvent::RequestRenameProfile;
                                input.consume_key(Modifiers::NONE, egui::Key::F2);
                                break;
                            }
                            egui::Key::F3 if modifiers.is_none() => {
                                event = MappingConfigEvent::RequestCreateProfile;
                                input.consume_key(Modifiers::NONE, egui::Key::F3);
                                break;
                            }
                            egui::Key::F4 if modifiers.is_none() => {
                                event = MappingConfigEvent::RequestDeleteProfile;
                                input.consume_key(Modifiers::NONE, egui::Key::F4);
                                break;
                            }
                            egui::Key::F5 if modifiers.is_none() => {
                                event = MappingConfigEvent::RequestSaveAsProfile;
                                input.consume_key(Modifiers::NONE, egui::Key::F5);
                                break;
                            }
                            _ => {}
                        }
                    }
                }
            });
        }

        event
    }

    /// Show key input dialog
    pub fn show_key_input_dialog(&mut self, ctx: &egui::Context, pos: &MappingPos) -> Option<Key> {
        if !self.key_input_dialog.is_visible() {
            return None;
        }

        let mut should_close = false;
        let mut captured_key = None;

        match self
            .key_input_dialog
            .set_message(&tf!(
                "mapping-config-dialog-create-message",
                "x" => pos.x,
                "y" => pos.y
            ))
            .show(ctx)
        {
            ModalDialogResult::CapturedKey(key) => {
                captured_key = Some(key);
                should_close = true;
            }
            ModalDialogResult::Canceled => {
                should_close = true;
            }
            _ => {}
        }

        if should_close {
            self.key_input_dialog.reset();
        }
        captured_key
    }

    /// Show delete confirmation dialog
    pub fn show_delete_confirm_dialog(
        &mut self,
        ctx: &egui::Context,
        key: Key,
        pos: &MappingPos,
    ) -> Option<bool> {
        if !self.delete_mapping_dialog.is_visible() {
            return None;
        }

        let mut should_close = false;
        let mut result = None;

        match self
            .delete_mapping_dialog
            .set_message(&tf!(
                "mapping-config-dialog-delete-message",
                "key" => format!("{:?}", key),
                "x" => pos.x.to_string(),
                "y" => pos.y.to_string()
            ))
            .show(ctx)
        {
            ModalDialogResult::Confirmed => {
                result = Some(true);
                should_close = true;
            }
            ModalDialogResult::Canceled => {
                result = Some(false);
                should_close = true;
            }
            _ => {}
        }

        if should_close {
            self.delete_mapping_dialog.reset();
        }
        result
    }

    /// Show override confirmation dialog
    pub fn show_override_confirm_dialog(
        &mut self,
        ctx: &egui::Context,
        key: Key,
        pos: &MappingPos,
        new_pos: &MappingPos,
    ) -> Option<bool> {
        if !self.override_mapping_dialog.is_visible() {
            return None;
        }

        let mut should_close = false;
        let mut result = None;

        match self
            .override_mapping_dialog
            .set_message(&tf!(
                "mapping-config-dialog-override-message",
                "key" => format!("{:?}", key),
                "old_x" => pos.x.to_string(),
                "old_y" => pos.y.to_string(),
                "new_x" => new_pos.x.to_string(),
                "new_y" => new_pos.y.to_string()
            ))
            .show(ctx)
        {
            ModalDialogResult::Confirmed => {
                result = Some(true);
                should_close = true;
            }
            ModalDialogResult::Canceled => {
                result = Some(false);
                should_close = true;
            }
            _ => {}
        }

        if should_close {
            self.override_mapping_dialog.reset();
        }
        result
    }

    pub fn any_dialog_open(&self) -> bool {
        self.key_input_dialog.is_visible()
            || self.delete_mapping_dialog.is_visible()
            || self.override_mapping_dialog.is_visible()
            || self.rename_dialog.is_visible()
            || self.help_dialog.is_visible()
    }

    pub fn is_input_dialog_open(&self) -> bool { self.key_input_dialog.is_visible() }

    pub fn is_delete_dialog_open(&self) -> bool { self.delete_mapping_dialog.is_visible() }

    pub fn is_override_dialog_open(&self) -> bool { self.override_mapping_dialog.is_visible() }

    pub fn is_rename_dialog_open(&self) -> bool { self.rename_dialog.is_visible() }

    pub fn is_help_dialog_open(&self) -> bool { self.help_dialog.is_visible() }

    pub fn get_pos(&self) -> Option<MappingPos> { self.pos }

    pub fn get_delete_target(&self) -> Option<(Key, MappingPos)> {
        self.delete_target_key
            .and_then(|key| self.delete_target_pos.map(|pos| (key, pos)).or(None))
    }

    #[allow(clippy::type_complexity)]
    pub fn get_override_target(&self) -> Option<(Key, MappingPos, MappingPos)> {
        self.override_key.and_then(|key| {
            self.override_pos.and_then(|pos| {
                self.override_new_pos
                    .map(|new_pos| (key, pos, new_pos))
                    .or(None)
            })
        })
    }

    /// Request to show input dialog (expects percentage coordinates 0.0-1.0)
    pub fn request_input_dialog(&mut self, pos: &MappingPos) {
        self.pos = Some(*pos);
        self.key_input_dialog.set_visible(true);
    }

    /// Request to show delete dialog (expects percentage coordinates 0.0-1.0)
    pub fn request_delete_dialog(&mut self, key: Key, pos: &MappingPos) {
        self.delete_target_key = Some(key);
        self.delete_target_pos = Some(*pos);
        self.delete_mapping_dialog.set_visible(true);
    }

    /// Request to show override confirmation dialog (expects percentage coordinates 0.0-1.0)
    pub fn request_override_dialog(&mut self, key: Key, pos: &MappingPos, new_pos: &MappingPos) {
        self.override_key = Some(key);
        self.override_pos = Some(*pos);
        self.override_new_pos = Some(*new_pos);
        self.override_mapping_dialog.set_visible(true);
    }

    pub fn request_rename_dialog(&mut self, current_name: &str) {
        self.rename_dialog
            .set_message(&t!("mapping-config-profile-label"))
            .set_text_input(current_name)
            .set_visible(true);
    }

    pub fn show_rename_dialog(&mut self, ctx: &egui::Context) -> Option<String> {
        if !self.rename_dialog.is_visible() {
            return None;
        }

        let mut should_close = false;
        let mut result = None;

        match self.rename_dialog.show(ctx) {
            ModalDialogResult::TextInput(new_name) => {
                result = Some(new_name);
                should_close = true;
            }
            ModalDialogResult::Canceled => {
                should_close = true;
            }
            _ => {}
        }

        if should_close {
            self.rename_dialog.reset();
        }

        result
    }

    pub fn request_help_dialog(&mut self) {
        self.help_dialog
            .set_message(&t!("mapping-config-help-message"))
            .set_visible(true);
    }

    pub fn show_help_dialog(&mut self, ctx: &egui::Context) -> bool {
        if !self.help_dialog.is_visible() {
            return false;
        }

        let mut should_close = false;

        match self.help_dialog.show(ctx) {
            ModalDialogResult::Confirmed | ModalDialogResult::Canceled => {
                should_close = true;
            }
            _ => {}
        }

        if should_close {
            self.help_dialog.reset();
        }

        should_close
    }
}
