//! Mapping configuration UI
//!
//! This module provides the UI overlay for configuring key mappings on the device screen.
//! It allows users to add, delete, and manage key mappings visually.

use {
    super::{
        super::{
            coords::{MappingCoordSys, ScrcpyCoordSys, VisualCoordSys},
            utils::extract_position,
        },
        theme::AppColors,
    },
    crate::{config::mapping::KeyMapping, t},
    eframe::egui::{self, Color32, FontId, Pos2, Stroke},
    egui::Modifiers,
};

const MAPPING_WINDOW_ID: &str = "mapping_config_overlay";

pub struct MappingDrawParams<'a> {
    pub mappings: &'a KeyMapping,
    pub profile_name: Option<&'a str>,
    pub video_rect: egui::Rect,
    pub visual_coords: &'a VisualCoordSys,
    pub scrcpy_coords: &'a ScrcpyCoordSys,
    pub mapping_coords: &'a MappingCoordSys,
}
/// Events generated by the mapping config window
#[derive(Debug, Clone)]
pub enum MappingConfigEvent {
    None,
    Close,
    AddMapping(Pos2),
    DeleteMapping(Pos2),
    RenameProfile,
    NewProfile,
    DeleteProfile,
    SaveAsProfile,
    ShowHelp,
    SwitchProfile,
    NextProfile,
    PrevProfile,
}

/// Mapping configuration overlay UI
pub struct MappingConfigOverlay {}

impl MappingConfigOverlay {
    pub fn new() -> Self { Self {} }

    pub fn draw(&mut self, ctx: &egui::Context, params: MappingDrawParams) -> MappingConfigEvent {
        let mut event = MappingConfigEvent::None;
        let colors = AppColors::from_context(ctx);

        egui::Area::new(egui::Id::new(MAPPING_WINDOW_ID))
            .fixed_pos(params.video_rect.min)
            .interactable(false)
            .order(egui::Order::Middle)
            .show(ctx, |ui| {
                let painter = ui.painter();

                painter.rect_filled(
                    params.video_rect,
                    0.0,
                    Color32::from_rgba_premultiplied(0, 0, 0, 180),
                );

                painter.text(
                    Pos2::new(params.video_rect.center().x, params.video_rect.top() + 20.0),
                    egui::Align2::CENTER_TOP,
                    t!("mapping-config-title"),
                    FontId::proportional(18.0),
                    Color32::WHITE,
                );

                let instructions = [
                    t!("mapping-config-instruction-help"),
                    t!("mapping-config-instruction-exit"),
                ];
                instructions.iter().enumerate().for_each(|(i, text)| {
                    painter.text(
                        Pos2::new(
                            params.video_rect.center().x,
                            params.video_rect.top() + 50.0 + i as f32 * 20.0,
                        ),
                        egui::Align2::CENTER_TOP,
                        text,
                        FontId::proportional(12.0),
                        Color32::LIGHT_GRAY,
                    );
                });

                params.mappings.read().iter().for_each(|(key, action)| {
                    if let Some(percent_pos) = extract_position(action) {
                        let screen_pos = params.visual_coords.from_mapping(
                            &percent_pos,
                            &params.video_rect,
                            params.scrcpy_coords,
                            params.mapping_coords,
                        );

                        painter.circle_filled(screen_pos, 12.0, colors.mapping_circle_fill);
                        painter.circle_stroke(
                            screen_pos,
                            12.0,
                            Stroke::new(2.0, colors.mapping_circle_stroke),
                        );

                        let key_text = format!("{:?}", key);
                        painter.text(
                            Pos2::new(screen_pos.x, screen_pos.y - 15.0),
                            egui::Align2::CENTER_BOTTOM,
                            &key_text,
                            FontId::proportional(12.0),
                            Color32::WHITE,
                        );
                    }
                });

                if let Some(name) = params.profile_name {
                    let profile_text = format!("{} {}", t!("mapping-config-profile-label"), name);
                    painter.text(
                        Pos2::new(
                            params.video_rect.center().x,
                            params.video_rect.top() + 100.0,
                        ),
                        egui::Align2::CENTER_TOP,
                        &profile_text,
                        FontId::proportional(14.0),
                        Color32::LIGHT_GRAY,
                    );
                }
            });

        ctx.input(|input| {
            if input.pointer.primary_clicked()
                && let Some(click_pos) = input.pointer.interact_pos()
                && params.video_rect.contains(click_pos)
            {
                event = MappingConfigEvent::AddMapping(click_pos);
            }

            if input.pointer.secondary_clicked()
                && let Some(click_pos) = input.pointer.interact_pos()
                && params.video_rect.contains(click_pos)
            {
                event = MappingConfigEvent::DeleteMapping(click_pos);
            }
        });

        ctx.input_mut(|input| {
            for e in &input.events {
                if let egui::Event::Key {
                    key,
                    pressed: true,
                    repeat: false,
                    modifiers,
                    ..
                } = e
                {
                    match key {
                        egui::Key::Escape if modifiers.is_none() => {
                            event = MappingConfigEvent::Close;
                            input.consume_key(Modifiers::NONE, egui::Key::Escape);
                            break;
                        }
                        egui::Key::F1 if modifiers.is_none() => {
                            event = MappingConfigEvent::ShowHelp;
                            input.consume_key(Modifiers::NONE, egui::Key::F1);
                            break;
                        }
                        egui::Key::F2 if modifiers.is_none() => {
                            event = MappingConfigEvent::RenameProfile;
                            input.consume_key(Modifiers::NONE, egui::Key::F2);
                            break;
                        }
                        egui::Key::F3 if modifiers.is_none() => {
                            event = MappingConfigEvent::NewProfile;
                            input.consume_key(Modifiers::NONE, egui::Key::F3);
                            break;
                        }
                        egui::Key::F4 if modifiers.is_none() => {
                            event = MappingConfigEvent::DeleteProfile;
                            input.consume_key(Modifiers::NONE, egui::Key::F4);
                            break;
                        }
                        egui::Key::F5 if modifiers.is_none() => {
                            event = MappingConfigEvent::SaveAsProfile;
                            input.consume_key(Modifiers::NONE, egui::Key::F5);
                            break;
                        }
                        egui::Key::F6 if modifiers.is_none() => {
                            event = MappingConfigEvent::SwitchProfile;
                            input.consume_key(Modifiers::NONE, egui::Key::F6);
                            break;
                        }
                        egui::Key::F7 if modifiers.is_none() => {
                            event = MappingConfigEvent::PrevProfile;
                            input.consume_key(Modifiers::NONE, egui::Key::F7);
                            break;
                        }
                        egui::Key::F8 if modifiers.is_none() => {
                            event = MappingConfigEvent::NextProfile;
                            input.consume_key(Modifiers::NONE, egui::Key::F8);
                            break;
                        }
                        _ => {}
                    }
                }
            }
        });

        event
    }
}
