use {
    super::utils::{device_to_screen_coords, extract_position},
    crate::config::mapping::{Key, KeyMapping},
    eframe::egui::{self, Color32, FontId, Pos2, Stroke},
    egui::{Modal, Modifiers},
};

const BUTTON_SIZE: (f32, f32) = (80.0, 30.0);

/// Events generated by the mapping config window
#[derive(Debug, Clone)]
pub enum MappingConfigEvent {
    None,
    Close,
    RequestAddMapping(Pos2),
    RequestDeleteMapping(Pos2),
}

/// Mapping configuration UI state
#[derive(Debug, Default)]
pub struct MappingConfigWindow {
    /// Whether the config window is visible
    pub visible: bool,

    /// Pending key input position (device coordinates)
    pending_input: Option<(u32, u32)>,

    /// Input dialog state
    input_dialog_open: bool,
    input_key: Option<Key>,

    /// Delete confirmation dialog state
    delete_confirm_open: bool,
    delete_target_key: Option<Key>,
    delete_target_pos: Option<(u32, u32)>,
}

impl MappingConfigWindow {
    pub fn new() -> Self { Self::default() }

    pub fn toggle(&mut self) {
        self.visible = !self.visible;
        if !self.visible {
            self.reset_state();
        }
    }

    pub fn hide(&mut self) {
        self.visible = false;
        self.reset_state();
    }

    fn reset_state(&mut self) {
        self.pending_input = None;
        self.input_dialog_open = false;
        self.input_key.take();
        self.delete_confirm_open = false;
        self.delete_target_key = None;
        self.delete_target_pos = None;
    }

    /// Draw the mapping configuration overlay
    pub fn draw(
        &mut self,
        ctx: &egui::Context,
        mappings: &KeyMapping,
        trans_params: &super::utils::CoordinatesTransformParams,
    ) -> MappingConfigEvent {
        if !self.visible {
            return MappingConfigEvent::None;
        }

        let video_rect = trans_params.video_rect;

        let mut event = MappingConfigEvent::None;

        // Draw semi-transparent overlay with interaction to consume events
        egui::Area::new(egui::Id::new("mapping_config_overlay"))
            .fixed_pos(video_rect.min)
            .interactable(true)
            .show(ctx, |ui| {
                // Create an invisible button covering the entire video rect to capture clicks
                let response = ui.allocate_rect(video_rect, egui::Sense::click());

                let painter = ui.painter();

                // Draw semi-transparent background
                painter.rect_filled(
                    video_rect,
                    0.0,
                    Color32::from_rgba_premultiplied(0, 0, 0, 180),
                );

                // Draw title
                painter.text(
                    Pos2::new(video_rect.center().x, video_rect.top() + 20.0),
                    egui::Align2::CENTER_TOP,
                    "Mapping Configuration Mode",
                    FontId::proportional(20.0),
                    Color32::WHITE,
                );

                // Draw instructions
                let instructions = [
                    "Left Click: Add key mapping",
                    "Right Click: Delete nearest mapping",
                    "Press ESC to exit",
                ];
                instructions.iter().enumerate().for_each(|(i, text)| {
                    painter.text(
                        Pos2::new(
                            video_rect.center().x,
                            video_rect.top() + 50.0 + i as f32 * 20.0,
                        ),
                        egui::Align2::CENTER_TOP,
                        *text,
                        FontId::proportional(14.0),
                        Color32::LIGHT_GRAY,
                    );
                });

                // Draw existing mappings
                mappings.lock().iter().for_each(|(key, action)| {
                    if let Some(screen_pos) = extract_position(action)
                        .and_then(|device_pos| device_to_screen_coords(device_pos, trans_params))
                    {
                        // Draw circle marker
                        painter.circle_filled(screen_pos, 8.0, Color32::from_rgb(100, 200, 255));
                        painter.circle_stroke(screen_pos, 8.0, Stroke::new(2.0, Color32::WHITE));

                        // Draw key label
                        let key_text = format!("{:?}", key);
                        painter.text(
                            Pos2::new(screen_pos.x, screen_pos.y - 15.0),
                            egui::Align2::CENTER_BOTTOM,
                            &key_text,
                            FontId::proportional(12.0),
                            Color32::WHITE,
                        );
                    }
                });

                // Handle clicks on the overlay
                if response.clicked() {
                    // Left click - request to add mapping
                    if let Some(click_pos) = response.interact_pointer_pos() {
                        event = MappingConfigEvent::RequestAddMapping(click_pos);
                    }
                } else if response.secondary_clicked() {
                    // Right click - request to delete nearest mapping
                    if let Some(click_pos) = response.interact_pointer_pos() {
                        event = MappingConfigEvent::RequestDeleteMapping(click_pos);
                    }
                }

                // Check for ESC key to exit
                if !self.input_dialog_open && !self.delete_confirm_open {
                    ui.input_mut(|input| {
                        for e in &input.events {
                            if let egui::Event::Key {
                            key,
                            pressed: true,
                            repeat: false,
                            modifiers,
                            ..
                        } = e
                            // Only capture ESC without modifiers
                            && *key == egui::Key::Escape
                            && modifiers.is_none()
                            {
                                event = MappingConfigEvent::Close;

                                // Prevent further processing
                                input.consume_key(Modifiers::NONE, egui::Key::Escape);
                                break;
                            }
                        }
                    });
                }
            });

        event
    }
}

impl MappingConfigWindow {
    /// Show key input dialog
    pub fn show_key_input_dialog(
        &mut self,
        ctx: &egui::Context,
        device_pos: (u32, u32),
    ) -> Option<Key> {
        if !self.input_dialog_open {
            return None;
        }

        let mut captured = None;
        let mut should_close = false;

        Modal::new("key_input_dialog".into()).show(ctx, |ui| {
            ui.vertical_centered(|ui| {
                ui.spacing_mut().item_spacing.y = 20.0;
                // Drao dialog content
                ui.label(format!("Position: ({}, {})", device_pos.0, device_pos.1));
                ui.separator();
                ui.horizontal_centered(|ui| {
                    ui.label("Press a key or ESC to cancel");
                });

                // Capture key input
                ui.input_mut(|input| {
                    for event in &input.events {
                        if let egui::Event::Key {
                            key,
                            pressed: true,
                            repeat: false,
                            modifiers,
                            ..
                        } = event
                            // Only capture non-modifier keys without modifiers
                            && modifiers.is_none()
                        {
                            if *key == egui::Key::Escape {
                                // Cancel input
                                captured = None;
                            } else {
                                // Capture the key
                                captured = Some(*key);
                            }

                            should_close = true;

                            // Prevent further processing
                            input.consume_key(Modifiers::NONE, *key);
                            break;
                        }
                    }
                });
            });
        });

        if should_close {
            self.input_dialog_open = false;
            self.input_key.take();
            self.pending_input = None;
        }

        captured
    }

    /// Show delete confirmation dialog
    pub fn show_delete_confirm_dialog(
        &mut self,
        ctx: &egui::Context,
        nearest_key: Key,
        nearest_pos: (u32, u32),
    ) -> Option<bool> {
        if !self.delete_confirm_open {
            return None;
        }

        let mut result = None;
        let mut should_close = false;

        egui::Modal::new("delete_confirm_dialog".into()).show(ctx, |ui| {
            ui.vertical_centered(|ui| {
                ui.spacing_mut().item_spacing.y = 10.0;

                // Drao dialog content
                ui.label("Delete mapping?");
                ui.label(format!(
                    "{:?}: ({}, {})",
                    nearest_key, nearest_pos.0, nearest_pos.1
                ));
                ui.separator();

                // Confirm and Cancel buttons
                ui.horizontal_centered(|ui| {
                    ui.spacing_mut().item_spacing.x = 20.0;
                    if ui
                        .add_sized(BUTTON_SIZE, egui::Button::new("Confirm"))
                        .clicked()
                    {
                        result = Some(true);
                        should_close = true;
                    }
                    if ui
                        .add_sized(BUTTON_SIZE, egui::Button::new("Cancel"))
                        .clicked()
                    {
                        result = Some(false);
                        should_close = true;
                    }
                });

                // Capture ESC key to cancel
                ui.input_mut(|input| {
                    for event in &input.events {
                        if let egui::Event::Key {
                            key,
                            pressed: true,
                            repeat: false,
                            modifiers,
                            ..
                        } = event
                            // Only capture ESC without modifiers
                            && *key == egui::Key::Escape
                            && modifiers.is_none()
                        {
                            result = Some(false);
                            should_close = true;

                            // Prevent further processing
                            input.consume_key(Modifiers::NONE, egui::Key::Escape);
                            break;
                        }
                    }
                });
            });
        });

        if should_close {
            self.delete_confirm_open = false;
            self.delete_target_key = None;
            self.delete_target_pos = None;
        }

        result
    }

    pub fn is_input_dialog_open(&self) -> bool { self.input_dialog_open }

    pub fn is_delete_dialog_open(&self) -> bool { self.delete_confirm_open }

    pub fn get_pending_input(&self) -> Option<(u32, u32)> { self.pending_input }

    pub fn get_delete_target(&self) -> Option<(Key, (u32, u32))> {
        self.delete_target_key
            .and_then(|key| self.delete_target_pos.map(|pos| (key, pos)).or(None))
    }

    /// Request to show input dialog
    pub fn request_input_dialog(&mut self, device_pos: (u32, u32)) {
        self.pending_input = Some(device_pos);
        self.input_dialog_open = true;
    }

    /// Request to show delete dialog
    pub fn request_delete_dialog(&mut self, key: Key, pos: (u32, u32)) {
        self.delete_target_key = Some(key);
        self.delete_target_pos = Some(pos);
        self.delete_confirm_open = true;
    }
}
