use {
    super::{
        super::utils::{CoordinatesTransformParams, device_to_screen_coords, extract_position},
        dialog::{ModalDialog, ModalDialogResult},
    },
    crate::config::mapping::{Key, KeyMapping},
    eframe::egui::{self, Color32, FontId, Pos2, Stroke},
    egui::Modifiers,
};
/// Events generated by the mapping config window
#[derive(Debug, Clone)]
pub enum MappingConfigEvent {
    None,
    Close,
    RequestAddMapping(Pos2),
    RequestDeleteMapping(Pos2),
}

/// Mapping configuration UI state
pub struct MappingConfigWindow {
    /// Whether the config window is visible
    pub visible: bool,

    /// Pending key input position (percentage coordinates 0.0-1.0)
    pos: Option<(f32, f32)>,

    /// Input dialog state
    key_input_dialog: ModalDialog,
    key: Option<Key>,

    /// Delete confirmation dialog state
    delete_mapping_dialog: ModalDialog,
    delete_target_key: Option<Key>,
    delete_target_pos: Option<(f32, f32)>,

    /// Override confirmation dialog state
    override_mapping_dialog: ModalDialog,
    override_key: Option<Key>,
    override_pos: Option<(f32, f32)>,
    override_new_pos: Option<(f32, f32)>,
}

impl MappingConfigWindow {
    pub fn new() -> Self {
        Self {
            visible: false,

            pos: None,

            key_input_dialog: ModalDialog::new("key_input_dialog")
                .with_title("Create Mapping")
                .with_key_capture(true),
            key: None,

            delete_mapping_dialog: ModalDialog::new("delete_mapping_dialog")
                .with_title("Delete Mapping"),
            delete_target_key: None,
            delete_target_pos: None,

            override_mapping_dialog: ModalDialog::new("override_mapping_dialog")
                .with_title("Override Mapping"),
            override_key: None,
            override_pos: None,
            override_new_pos: None,
        }
    }

    pub fn toggle(&mut self) {
        self.visible = !self.visible;
        if !self.visible {
            self.reset();
        }
    }

    pub fn hide(&mut self) {
        self.visible = false;
        self.reset();
    }

    fn reset(&mut self) {
        self.pos = None;

        self.key_input_dialog.reset();
        self.key = None;

        self.delete_mapping_dialog.reset();
        self.delete_target_key = None;
        self.delete_target_pos = None;

        self.override_mapping_dialog.reset();
        self.override_key = None;
        self.override_pos = None;
        self.override_new_pos = None;
    }

    pub fn is_visible(&self) -> bool { self.visible }

    /// Draw the mapping configuration overlay
    pub fn draw(
        &mut self,
        ctx: &egui::Context,
        mappings: &KeyMapping,
        trans_params: &CoordinatesTransformParams,
    ) -> MappingConfigEvent {
        if !self.visible {
            return MappingConfigEvent::None;
        }

        let video_rect = trans_params.video_rect;

        let mut event = MappingConfigEvent::None;

        // Draw semi-transparent overlay with interaction to consume events
        egui::Area::new(egui::Id::new("mapping_config_overlay"))
            .fixed_pos(video_rect.min)
            .interactable(true)
            .show(ctx, |ui| {
                // Create an invisible button covering the entire video rect to capture clicks
                let response = ui.allocate_rect(video_rect, egui::Sense::click());

                let painter = ui.painter();

                // Draw semi-transparent background
                painter.rect_filled(
                    video_rect,
                    0.0,
                    Color32::from_rgba_premultiplied(0, 0, 0, 180),
                );

                // Draw title
                painter.text(
                    Pos2::new(video_rect.center().x, video_rect.top() + 20.0),
                    egui::Align2::CENTER_TOP,
                    "Mapping Configuration Mode",
                    FontId::proportional(20.0),
                    Color32::WHITE,
                );

                // Draw instructions
                let instructions = [
                    "Left Click: Add key mapping",
                    "Right Click: Delete nearest mapping",
                    "Press ESC to exit",
                ];
                instructions.iter().enumerate().for_each(|(i, text)| {
                    painter.text(
                        Pos2::new(
                            video_rect.center().x,
                            video_rect.top() + 50.0 + i as f32 * 20.0,
                        ),
                        egui::Align2::CENTER_TOP,
                        *text,
                        FontId::proportional(14.0),
                        Color32::LIGHT_GRAY,
                    );
                });

                // Draw existing mappings
                // Note: Profile 中的坐标是百分比 (0.0-1.0)
                mappings.read().iter().for_each(|(key, action)| {
                    if let Some(percent_pos) = extract_position(action)
                        && let Some(screen_pos) = device_to_screen_coords(percent_pos, trans_params)
                    {
                        // Draw circle marker
                        painter.circle_filled(screen_pos, 8.0, Color32::from_rgb(100, 200, 255));
                        painter.circle_stroke(screen_pos, 8.0, Stroke::new(2.0, Color32::WHITE));

                        // Draw key label
                        let key_text = format!("{:?}", key);
                        painter.text(
                            Pos2::new(screen_pos.x, screen_pos.y - 15.0),
                            egui::Align2::CENTER_BOTTOM,
                            &key_text,
                            FontId::proportional(12.0),
                            Color32::WHITE,
                        );
                    }
                });

                // Handle clicks on the overlay
                if response.clicked() {
                    // Left click - request to add mapping
                    if let Some(click_pos) = response.interact_pointer_pos() {
                        event = MappingConfigEvent::RequestAddMapping(click_pos);
                    }
                } else if response.secondary_clicked() {
                    // Right click - request to delete nearest mapping
                    if let Some(click_pos) = response.interact_pointer_pos() {
                        event = MappingConfigEvent::RequestDeleteMapping(click_pos);
                    }
                }

                // Check for ESC key to exit
                if !self.any_dialog_open() {
                    ui.input_mut(|input| {
                        for e in &input.events {
                            if let egui::Event::Key {
                            key,
                            pressed: true,
                            repeat: false,
                            modifiers,
                            ..
                        } = e
                            // Only capture ESC without modifiers
                            && *key == egui::Key::Escape
                            && modifiers.is_none()
                            {
                                event = MappingConfigEvent::Close;

                                // Prevent further processing
                                input.consume_key(Modifiers::NONE, egui::Key::Escape);
                                break;
                            }
                        }
                    });
                }
            });

        event
    }

    /// Show key input dialog
    ///
    /// Displays position as percentage coordinates (0-100%)
    pub fn show_key_input_dialog(
        &mut self,
        ctx: &egui::Context,
        device_pos: (f32, f32),
    ) -> Option<Key> {
        if !self.key_input_dialog.is_visible() {
            return None;
        }

        let mut should_close = false;
        let mut captured_key = None;

        // Display as percentage (0-100%)
        let percent_x = device_pos.0 * 100.0;
        let percent_y = device_pos.1 * 100.0;

        match self
            .key_input_dialog
            .set_message(&format!(
                "\nPosition: ({:.2}%, {:.2}%)\n\nPress a key or ESC to cancel...\n",
                percent_x, percent_y
            ))
            .show(ctx)
        {
            ModalDialogResult::CapturedKey(key) => {
                captured_key = Some(key);
                should_close = true;
            }
            ModalDialogResult::Canceled => {
                should_close = true;
            }
            _ => {}
        }

        if should_close {
            self.key_input_dialog.reset();
        }
        captured_key
    }

    /// Show delete confirmation dialog
    ///
    /// Displays position as percentage coordinates (0-100%)
    pub fn show_delete_confirm_dialog(
        &mut self,
        ctx: &egui::Context,
        key: Key,
        pos: (f32, f32),
    ) -> Option<bool> {
        if !self.delete_mapping_dialog.is_visible() {
            return None;
        }

        let mut shoudl_close = false;
        let mut result = None;

        // Display as percentage (0-100%)
        let percent_x = pos.0 * 100.0;
        let percent_y = pos.1 * 100.0;

        match self
            .delete_mapping_dialog
            .set_message(&format!(
                "\n{:?}: ({:.2}%, {:.2}%)?\n",
                key, percent_x, percent_y
            ))
            .show(ctx)
        {
            ModalDialogResult::Confirmed => {
                result = Some(true);
                shoudl_close = true;
            }
            ModalDialogResult::Canceled => {
                result = Some(false);
                shoudl_close = true;
            }
            _ => {}
        }

        if shoudl_close {
            self.delete_mapping_dialog.reset();
        }
        result
    }

    /// Show override confirmation dialog
    ///
    /// Displays positions as percentage coordinates (0-100%)
    pub fn show_override_confirm_dialog(
        &mut self,
        ctx: &egui::Context,
        key: Key,
        pos: (f32, f32),
        new_pos: (f32, f32),
    ) -> Option<bool> {
        if !self.override_mapping_dialog.is_visible() {
            return None;
        }

        let mut should_close = false;
        let mut result = None;

        // Display as percentage (0-100%)
        let percent_x = pos.0 * 100.0;
        let percent_y = pos.1 * 100.0;
        let new_percent_x = new_pos.0 * 100.0;
        let new_percent_y = new_pos.1 * 100.0;

        match self
            .override_mapping_dialog
            .set_message(&format!(
                "\n{:?}: ({:.2}%, {:.2}%) is already mapped.\n\nOverride to new position ({:.2}%, {:.2}%)?\n",
                key, percent_x, percent_y, new_percent_x, new_percent_y
            ))
            .show(ctx)
        {
            ModalDialogResult::Confirmed => {
                result = Some(true);
                should_close = true;
            }
            ModalDialogResult::Canceled => {
                result = Some(false);
                should_close = true;
            }
            _ => {}
        }

        if should_close {
            self.override_mapping_dialog.reset();
        }
        result
    }

    pub fn any_dialog_open(&self) -> bool {
        self.key_input_dialog.is_visible()
            || self.delete_mapping_dialog.is_visible()
            || self.override_mapping_dialog.is_visible()
    }

    pub fn is_input_dialog_open(&self) -> bool { self.key_input_dialog.is_visible() }

    pub fn is_delete_dialog_open(&self) -> bool { self.delete_mapping_dialog.is_visible() }

    pub fn is_override_dialog_open(&self) -> bool { self.override_mapping_dialog.is_visible() }

    pub fn get_pos(&self) -> Option<(f32, f32)> { self.pos }

    pub fn get_delete_target(&self) -> Option<(Key, (f32, f32))> {
        self.delete_target_key
            .and_then(|key| self.delete_target_pos.map(|pos| (key, pos)).or(None))
    }

    #[allow(clippy::type_complexity)]
    pub fn get_override_target(&self) -> Option<(Key, (f32, f32), (f32, f32))> {
        self.override_key.and_then(|key| {
            self.override_pos.and_then(|pos| {
                self.override_new_pos
                    .map(|new_pos| (key, pos, new_pos))
                    .or(None)
            })
        })
    }

    /// Request to show input dialog (expects percentage coordinates 0.0-1.0)
    pub fn request_input_dialog(&mut self, device_pos: (f32, f32)) {
        self.pos = Some(device_pos);
        self.key_input_dialog.set_visible(true);
    }

    /// Request to show delete dialog (expects percentage coordinates 0.0-1.0)
    pub fn request_delete_dialog(&mut self, key: Key, pos: (f32, f32)) {
        self.delete_target_key = Some(key);
        self.delete_target_pos = Some(pos);
        self.delete_mapping_dialog.set_visible(true);
    }

    /// Request to show override confirmation dialog (expects percentage coordinates 0.0-1.0)
    pub fn request_override_dialog(&mut self, key: Key, pos: (f32, f32), new_pos: (f32, f32)) {
        self.override_key = Some(key);
        self.override_pos = Some(pos);
        self.override_new_pos = Some(new_pos);
        self.override_mapping_dialog.set_visible(true);
    }
}
